/**
 */
package query.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import query.util.QueryAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class QueryItemProviderAdapterFactory extends QueryAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public QueryItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.QuerySurface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QuerySurfaceItemProvider querySurfaceItemProvider;

	/**
	 * This creates an adapter for a {@link query.QuerySurface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQuerySurfaceAdapter() {
		if (querySurfaceItemProvider == null) {
			querySurfaceItemProvider = new QuerySurfaceItemProvider(this);
		}

		return querySurfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.OutputInstalment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutputInstalmentItemProvider outputInstalmentItemProvider;

	/**
	 * This creates an adapter for a {@link query.OutputInstalment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutputInstalmentAdapter() {
		if (outputInstalmentItemProvider == null) {
			outputInstalmentItemProvider = new OutputInstalmentItemProvider(this);
		}

		return outputInstalmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.InputInstalment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputInstalmentItemProvider inputInstalmentItemProvider;

	/**
	 * This creates an adapter for a {@link query.InputInstalment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputInstalmentAdapter() {
		if (inputInstalmentItemProvider == null) {
			inputInstalmentItemProvider = new InputInstalmentItemProvider(this);
		}

		return inputInstalmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.SortInstalment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SortInstalmentItemProvider sortInstalmentItemProvider;

	/**
	 * This creates an adapter for a {@link query.SortInstalment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSortInstalmentAdapter() {
		if (sortInstalmentItemProvider == null) {
			sortInstalmentItemProvider = new SortInstalmentItemProvider(this);
		}

		return sortInstalmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.GroupInstalment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GroupInstalmentItemProvider groupInstalmentItemProvider;

	/**
	 * This creates an adapter for a {@link query.GroupInstalment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGroupInstalmentAdapter() {
		if (groupInstalmentItemProvider == null) {
			groupInstalmentItemProvider = new GroupInstalmentItemProvider(this);
		}

		return groupInstalmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.WhereInstalment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WhereInstalmentItemProvider whereInstalmentItemProvider;

	/**
	 * This creates an adapter for a {@link query.WhereInstalment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWhereInstalmentAdapter() {
		if (whereInstalmentItemProvider == null) {
			whereInstalmentItemProvider = new WhereInstalmentItemProvider(this);
		}

		return whereInstalmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.HavingInstalment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HavingInstalmentItemProvider havingInstalmentItemProvider;

	/**
	 * This creates an adapter for a {@link query.HavingInstalment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHavingInstalmentAdapter() {
		if (havingInstalmentItemProvider == null) {
			havingInstalmentItemProvider = new HavingInstalmentItemProvider(this);
		}

		return havingInstalmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.InnerjoinRels} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InnerjoinRelsItemProvider innerjoinRelsItemProvider;

	/**
	 * This creates an adapter for a {@link query.InnerjoinRels}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInnerjoinRelsAdapter() {
		if (innerjoinRelsItemProvider == null) {
			innerjoinRelsItemProvider = new InnerjoinRelsItemProvider(this);
		}

		return innerjoinRelsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.LeftOuterJoinRels} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LeftOuterJoinRelsItemProvider leftOuterJoinRelsItemProvider;

	/**
	 * This creates an adapter for a {@link query.LeftOuterJoinRels}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLeftOuterJoinRelsAdapter() {
		if (leftOuterJoinRelsItemProvider == null) {
			leftOuterJoinRelsItemProvider = new LeftOuterJoinRelsItemProvider(this);
		}

		return leftOuterJoinRelsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.RightOuterJoinRels} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RightOuterJoinRelsItemProvider rightOuterJoinRelsItemProvider;

	/**
	 * This creates an adapter for a {@link query.RightOuterJoinRels}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRightOuterJoinRelsAdapter() {
		if (rightOuterJoinRelsItemProvider == null) {
			rightOuterJoinRelsItemProvider = new RightOuterJoinRelsItemProvider(this);
		}

		return rightOuterJoinRelsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.FullOuterJoinRels} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FullOuterJoinRelsItemProvider fullOuterJoinRelsItemProvider;

	/**
	 * This creates an adapter for a {@link query.FullOuterJoinRels}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFullOuterJoinRelsAdapter() {
		if (fullOuterJoinRelsItemProvider == null) {
			fullOuterJoinRelsItemProvider = new FullOuterJoinRelsItemProvider(this);
		}

		return fullOuterJoinRelsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.FieldGPointer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FieldGPointerItemProvider fieldGPointerItemProvider;

	/**
	 * This creates an adapter for a {@link query.FieldGPointer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFieldGPointerAdapter() {
		if (fieldGPointerItemProvider == null) {
			fieldGPointerItemProvider = new FieldGPointerItemProvider(this);
		}

		return fieldGPointerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.FieldSPointer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FieldSPointerItemProvider fieldSPointerItemProvider;

	/**
	 * This creates an adapter for a {@link query.FieldSPointer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFieldSPointerAdapter() {
		if (fieldSPointerItemProvider == null) {
			fieldSPointerItemProvider = new FieldSPointerItemProvider(this);
		}

		return fieldSPointerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.MyTable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MyTableItemProvider myTableItemProvider;

	/**
	 * This creates an adapter for a {@link query.MyTable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMyTableAdapter() {
		if (myTableItemProvider == null) {
			myTableItemProvider = new MyTableItemProvider(this);
		}

		return myTableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.Field} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FieldItemProvider fieldItemProvider;

	/**
	 * This creates an adapter for a {@link query.Field}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFieldAdapter() {
		if (fieldItemProvider == null) {
			fieldItemProvider = new FieldItemProvider(this);
		}

		return fieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.Literal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LiteralItemProvider literalItemProvider;

	/**
	 * This creates an adapter for a {@link query.Literal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLiteralAdapter() {
		if (literalItemProvider == null) {
			literalItemProvider = new LiteralItemProvider(this);
		}

		return literalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.NullLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NullLiteralItemProvider nullLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link query.NullLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNullLiteralAdapter() {
		if (nullLiteralItemProvider == null) {
			nullLiteralItemProvider = new NullLiteralItemProvider(this);
		}

		return nullLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.Function} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionItemProvider functionItemProvider;

	/**
	 * This creates an adapter for a {@link query.Function}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionAdapter() {
		if (functionItemProvider == null) {
			functionItemProvider = new FunctionItemProvider(this);
		}

		return functionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.FunctionDef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionDefItemProvider functionDefItemProvider;

	/**
	 * This creates an adapter for a {@link query.FunctionDef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionDefAdapter() {
		if (functionDefItemProvider == null) {
			functionDefItemProvider = new FunctionDefItemProvider(this);
		}

		return functionDefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.Input} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputItemProvider inputItemProvider;

	/**
	 * This creates an adapter for a {@link query.Input}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputAdapter() {
		if (inputItemProvider == null) {
			inputItemProvider = new InputItemProvider(this);
		}

		return inputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.InputStringDef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputStringDefItemProvider inputStringDefItemProvider;

	/**
	 * This creates an adapter for a {@link query.InputStringDef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputStringDefAdapter() {
		if (inputStringDefItemProvider == null) {
			inputStringDefItemProvider = new InputStringDefItemProvider(this);
		}

		return inputStringDefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.InputIntDef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputIntDefItemProvider inputIntDefItemProvider;

	/**
	 * This creates an adapter for a {@link query.InputIntDef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputIntDefAdapter() {
		if (inputIntDefItemProvider == null) {
			inputIntDefItemProvider = new InputIntDefItemProvider(this);
		}

		return inputIntDefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.InputDateDef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputDateDefItemProvider inputDateDefItemProvider;

	/**
	 * This creates an adapter for a {@link query.InputDateDef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputDateDefAdapter() {
		if (inputDateDefItemProvider == null) {
			inputDateDefItemProvider = new InputDateDefItemProvider(this);
		}

		return inputDateDefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.InputBitsDef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputBitsDefItemProvider inputBitsDefItemProvider;

	/**
	 * This creates an adapter for a {@link query.InputBitsDef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputBitsDefAdapter() {
		if (inputBitsDefItemProvider == null) {
			inputBitsDefItemProvider = new InputBitsDefItemProvider(this);
		}

		return inputBitsDefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.InputFloatDef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputFloatDefItemProvider inputFloatDefItemProvider;

	/**
	 * This creates an adapter for a {@link query.InputFloatDef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputFloatDefAdapter() {
		if (inputFloatDefItemProvider == null) {
			inputFloatDefItemProvider = new InputFloatDefItemProvider(this);
		}

		return inputFloatDefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.CallQuerySurface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CallQuerySurfaceItemProvider callQuerySurfaceItemProvider;

	/**
	 * This creates an adapter for a {@link query.CallQuerySurface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCallQuerySurfaceAdapter() {
		if (callQuerySurfaceItemProvider == null) {
			callQuerySurfaceItemProvider = new CallQuerySurfaceItemProvider(this);
		}

		return callQuerySurfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.Type} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeItemProvider typeItemProvider;

	/**
	 * This creates an adapter for a {@link query.Type}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeAdapter() {
		if (typeItemProvider == null) {
			typeItemProvider = new TypeItemProvider(this);
		}

		return typeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.Subtype} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubtypeItemProvider subtypeItemProvider;

	/**
	 * This creates an adapter for a {@link query.Subtype}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubtypeAdapter() {
		if (subtypeItemProvider == null) {
			subtypeItemProvider = new SubtypeItemProvider(this);
		}

		return subtypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.Junction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JunctionItemProvider junctionItemProvider;

	/**
	 * This creates an adapter for a {@link query.Junction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJunctionAdapter() {
		if (junctionItemProvider == null) {
			junctionItemProvider = new JunctionItemProvider(this);
		}

		return junctionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.RootJunction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RootJunctionItemProvider rootJunctionItemProvider;

	/**
	 * This creates an adapter for a {@link query.RootJunction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRootJunctionAdapter() {
		if (rootJunctionItemProvider == null) {
			rootJunctionItemProvider = new RootJunctionItemProvider(this);
		}

		return rootJunctionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.JuncRelationship} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JuncRelationshipItemProvider juncRelationshipItemProvider;

	/**
	 * This creates an adapter for a {@link query.JuncRelationship}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJuncRelationshipAdapter() {
		if (juncRelationshipItemProvider == null) {
			juncRelationshipItemProvider = new JuncRelationshipItemProvider(this);
		}

		return juncRelationshipItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.Term} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TermItemProvider termItemProvider;

	/**
	 * This creates an adapter for a {@link query.Term}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTermAdapter() {
		if (termItemProvider == null) {
			termItemProvider = new TermItemProvider(this);
		}

		return termItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.EqualLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EqualLinkItemProvider equalLinkItemProvider;

	/**
	 * This creates an adapter for a {@link query.EqualLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEqualLinkAdapter() {
		if (equalLinkItemProvider == null) {
			equalLinkItemProvider = new EqualLinkItemProvider(this);
		}

		return equalLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.GreaterThanLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GreaterThanLinkItemProvider greaterThanLinkItemProvider;

	/**
	 * This creates an adapter for a {@link query.GreaterThanLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGreaterThanLinkAdapter() {
		if (greaterThanLinkItemProvider == null) {
			greaterThanLinkItemProvider = new GreaterThanLinkItemProvider(this);
		}

		return greaterThanLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.GreaterEqualThanLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GreaterEqualThanLinkItemProvider greaterEqualThanLinkItemProvider;

	/**
	 * This creates an adapter for a {@link query.GreaterEqualThanLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGreaterEqualThanLinkAdapter() {
		if (greaterEqualThanLinkItemProvider == null) {
			greaterEqualThanLinkItemProvider = new GreaterEqualThanLinkItemProvider(this);
		}

		return greaterEqualThanLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.LowerThanLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LowerThanLinkItemProvider lowerThanLinkItemProvider;

	/**
	 * This creates an adapter for a {@link query.LowerThanLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLowerThanLinkAdapter() {
		if (lowerThanLinkItemProvider == null) {
			lowerThanLinkItemProvider = new LowerThanLinkItemProvider(this);
		}

		return lowerThanLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.LowerEqualThanLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LowerEqualThanLinkItemProvider lowerEqualThanLinkItemProvider;

	/**
	 * This creates an adapter for a {@link query.LowerEqualThanLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLowerEqualThanLinkAdapter() {
		if (lowerEqualThanLinkItemProvider == null) {
			lowerEqualThanLinkItemProvider = new LowerEqualThanLinkItemProvider(this);
		}

		return lowerEqualThanLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.InLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InLinkItemProvider inLinkItemProvider;

	/**
	 * This creates an adapter for a {@link query.InLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInLinkAdapter() {
		if (inLinkItemProvider == null) {
			inLinkItemProvider = new InLinkItemProvider(this);
		}

		return inLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link query.LikeLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LikeLinkItemProvider likeLinkItemProvider;

	/**
	 * This creates an adapter for a {@link query.LikeLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLikeLinkAdapter() {
		if (likeLinkItemProvider == null) {
			likeLinkItemProvider = new LikeLinkItemProvider(this);
		}

		return likeLinkItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (querySurfaceItemProvider != null) querySurfaceItemProvider.dispose();
		if (outputInstalmentItemProvider != null) outputInstalmentItemProvider.dispose();
		if (inputInstalmentItemProvider != null) inputInstalmentItemProvider.dispose();
		if (sortInstalmentItemProvider != null) sortInstalmentItemProvider.dispose();
		if (groupInstalmentItemProvider != null) groupInstalmentItemProvider.dispose();
		if (whereInstalmentItemProvider != null) whereInstalmentItemProvider.dispose();
		if (havingInstalmentItemProvider != null) havingInstalmentItemProvider.dispose();
		if (innerjoinRelsItemProvider != null) innerjoinRelsItemProvider.dispose();
		if (leftOuterJoinRelsItemProvider != null) leftOuterJoinRelsItemProvider.dispose();
		if (rightOuterJoinRelsItemProvider != null) rightOuterJoinRelsItemProvider.dispose();
		if (fullOuterJoinRelsItemProvider != null) fullOuterJoinRelsItemProvider.dispose();
		if (fieldGPointerItemProvider != null) fieldGPointerItemProvider.dispose();
		if (fieldSPointerItemProvider != null) fieldSPointerItemProvider.dispose();
		if (myTableItemProvider != null) myTableItemProvider.dispose();
		if (fieldItemProvider != null) fieldItemProvider.dispose();
		if (literalItemProvider != null) literalItemProvider.dispose();
		if (nullLiteralItemProvider != null) nullLiteralItemProvider.dispose();
		if (functionItemProvider != null) functionItemProvider.dispose();
		if (functionDefItemProvider != null) functionDefItemProvider.dispose();
		if (inputItemProvider != null) inputItemProvider.dispose();
		if (inputStringDefItemProvider != null) inputStringDefItemProvider.dispose();
		if (inputIntDefItemProvider != null) inputIntDefItemProvider.dispose();
		if (inputDateDefItemProvider != null) inputDateDefItemProvider.dispose();
		if (inputBitsDefItemProvider != null) inputBitsDefItemProvider.dispose();
		if (inputFloatDefItemProvider != null) inputFloatDefItemProvider.dispose();
		if (callQuerySurfaceItemProvider != null) callQuerySurfaceItemProvider.dispose();
		if (typeItemProvider != null) typeItemProvider.dispose();
		if (subtypeItemProvider != null) subtypeItemProvider.dispose();
		if (junctionItemProvider != null) junctionItemProvider.dispose();
		if (rootJunctionItemProvider != null) rootJunctionItemProvider.dispose();
		if (juncRelationshipItemProvider != null) juncRelationshipItemProvider.dispose();
		if (termItemProvider != null) termItemProvider.dispose();
		if (equalLinkItemProvider != null) equalLinkItemProvider.dispose();
		if (greaterThanLinkItemProvider != null) greaterThanLinkItemProvider.dispose();
		if (greaterEqualThanLinkItemProvider != null) greaterEqualThanLinkItemProvider.dispose();
		if (lowerThanLinkItemProvider != null) lowerThanLinkItemProvider.dispose();
		if (lowerEqualThanLinkItemProvider != null) lowerEqualThanLinkItemProvider.dispose();
		if (inLinkItemProvider != null) inLinkItemProvider.dispose();
		if (likeLinkItemProvider != null) likeLinkItemProvider.dispose();
	}

}
